### ISSUE TITLE
Feature: User can View the NavBar and also the Monsters.

### ISSUE THREAD

**Issue by Sam-Castaneda13** [Sam-Castaneda13/front-end-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User's can view the Navbar and also View all of the Monsters

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The goal is to be able to View all 58 monsters and view the Navbar

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Create a HTML Skeleton with a Navbar and Div container for all the monsters
- [ ] Should fit both Mobile and Desktop views.
- [ ] Inside the Div have a dom creation make all the monsters
      - [ ]  First Fetch the Api data for the Monsters
      - [ ] Using the Dom Creation to render in all of the Monsters one by one.
      - [ ] The Dom Creation should produce a Picture of the monster and it's name.
- [ ] Each Monster should take up one-third of the page
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
