### ISSUE TITLE
Feature 2: User can Switch pages.

### ISSUE THREAD

**Issue by Sam-Castaneda13** [Sam-Castaneda13/front-end-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can Switch Pages from the main page to favorite page, random page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

It will change the page into the favorite page or the random page. This Will be indicated by the current page being colored yellow on the navbar.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create the new pages for the favorite page.
     - [ ] Must include:
     - [ ] Favorites Title underneath the Navbar
     - [ ] Change the Favorite in the Navbar to Yellow
     - [ ] Change the Other items white.
- [ ] Create the new page for the random page.
     - [ ] Must include:
     - [ ] Favorites Title underneath the Navbar
     - [ ] Change the Favorite in the Navbar to Yellow
     - [ ] Change the Other items white.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
