### ISSUE TITLE
Feature 3: User Can Filter out the Monsters

### ISSUE THREAD

**Issue by Sam-Castaneda13** [Sam-Castaneda13/front-end-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can filter to see Monsters based on which box is checked

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

It will pull up a menu to let the user choose which they would like to filter and also Remove monsters that are filtered.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] When clicked on the filter Icon open a menu.
- [ ] Inside the menu.
      - [ ] Allows User to choose if they want Monsters from DLC or Not
      - [ ] Allows User to choose which monsters are in a area.
      - [ ] Ask if the user confirms or cancel.
- [ ] Using HTMLInputElement to select the filter icon
- [ ] opens a dialog with selections
- [ ] changes the classes of the monsters to not be shown.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
