### ISSUE TITLE
Feature 4: User can select a Monster and see all its information

### ISSUE THREAD

**Issue by Sam-Castaneda13** [Sam-Castaneda13/front-end-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

When picture is clicked opens a new page and Shows new picture and information about the Monster

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User sees the more defined picture of the monster and The monsters information.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Opens a new page when clicked.
   - [ ] Render the page based on the Monsters information and picture
- [ ] The page should include information about the Monster
   - [ ]  Should include Picture
   - [ ] include Name
   - [ ] include type
   - [ ] include species
   - [ ] include description
   - [ ] include locations
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
