### ISSUE TITLE
Feature 5: User can favorite a Monster and it can be seen in Favorite Page.

### ISSUE THREAD

**Issue by Sam-Castaneda13** [Sam-Castaneda13/front-end-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The User can click on the star next to the monsters Name turning it yellow and making it a favorite. Then when the user checks the favorite page they can see all the monsters favorited.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

It will work as clicking on the star turning the color to show that it is favorited. Then when they change the page the monster will appear in the favorite page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] The star to favorite
    - [ ] When looking at the detailed page of a monster add a Star to the right
    - [ ] When star is clicked it turns yellow showing it is Favorited
    - [ ] Add a class to the monster saying it is a favorite.
- [ ] Changing to the favorite page
    - [ ] Can view the monster looks similar to the Main search page.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
